package com.andannn.melodify.core.database.model

import androidx.room.ColumnInfo

class AudioVideoMergedResult(
    @ColumnInfo(name = "video_id")
    val video_id: Long = 0,
    @ColumnInfo(name = "video_file_path")
    val video_path: String? = null,
    @ColumnInfo(name = "video_source_uri")
    val video_sourceUri: String? = null,
    @ColumnInfo(name = "video_title")
    val video_title: String? = null,
    @ColumnInfo(name = "video_duration")
    val video_duration: Int? = null,
    @ColumnInfo(name = "video_modified_date")
    val video_modifiedDate: Long? = null,
    @ColumnInfo(name = "video_size")
    val video_size: Int? = null,
    @ColumnInfo(name = "video_mime_type")
    val video_mimeType: String? = null,
    // video-specific
    @ColumnInfo(name = "video_width")
    val video_width: Int? = null,
    @ColumnInfo(name = "video_height")
    val video_height: Int? = null,
    @ColumnInfo(name = "video_orientation")
    val video_orientation: Int? = null,
    @ColumnInfo(name = "video_resolution")
    val video_resolution: String? = null,
    @ColumnInfo(name = "video_relative_path")
    val video_relativePath: String? = null,
    @ColumnInfo(name = "video_bucket_id")
    val video_bucketId: Long? = null,
    @ColumnInfo(name = "video_bucket_display_name")
    val video_bucketDisplayName: String? = null,
    @ColumnInfo(name = "video_volume_name")
    val video_volumeName: String? = null,
    @ColumnInfo(name = "video_album")
    val video_album: String? = null,
    @ColumnInfo(name = "video_artist")
    val video_artist: String? = null,
    @ColumnInfo(name = "video_date_added")
    val video_dateAdded: Long? = null,
    @ColumnInfo(name = "video_date_modified")
    val video_dateModified: Long? = null,
    @ColumnInfo(name = "video_deleted")
    val video_deleted: Int? = null,
    @ColumnInfo(name = "media_id")
    val audio_id: Long = 0,
    @ColumnInfo(name = "file_path")
    val audio_path: String? = null,
    @ColumnInfo(name = "source_uri")
    val audio_sourceUri: String? = null,
    @ColumnInfo(name = "media_title")
    val audio_title: String? = null,
    @ColumnInfo(name = "media_duration")
    val audio_duration: Int? = null,
    @ColumnInfo(name = "media_modified_date")
    val audio_modifiedDate: Long? = null,
    @ColumnInfo(name = "media_size")
    val audio_size: Int? = null,
    @ColumnInfo(name = "media_mime_type")
    val audio_mimeType: String? = null,
    @ColumnInfo(name = "media_album")
    val audio_album: String? = null,
    @ColumnInfo(name = "media_album_id")
    val audio_albumId: Long? = null,
    @ColumnInfo(name = "media_artist")
    val audio_artist: String? = null,
    @ColumnInfo(name = "media_artist_id")
    val audio_artistId: Long? = null,
    @ColumnInfo(name = "media_cd_track_number")
    val audio_cdTrackNumber: Int? = null,
    @ColumnInfo(name = "media_disc_number")
    val audio_discNumber: Int? = null,
    @ColumnInfo(name = "media_num_tracks")
    val audio_numTracks: Int? = null,
    @ColumnInfo(name = "media_bitrate")
    val audio_bitrate: Int? = null,
    @ColumnInfo(name = "media_genre")
    val audio_genre: String? = null,
    @ColumnInfo(name = "media_genre_id")
    val audio_genreId: Long? = null,
    @ColumnInfo(name = "media_year")
    val audio_year: String? = null,
    @ColumnInfo(name = "media_track")
    val audio_track: String? = null,
    @ColumnInfo(name = "media_composer")
    val audio_composer: String? = null,
    @ColumnInfo(name = "media_cover")
    val audio_cover: String? = null,
    @ColumnInfo(name = "deleted")
    val audio_deleted: Int? = null,
)
